### ISSUE TITLE
还有2种情况需要考虑

### ISSUE THREAD

**Issue by coolme200** [alibaba-archive/cache-dns#2]
1，域名配在HOSTS中无法读取
2，VIP无法读取IP（可以根据正则判断如果是IP的形式就直接访问）

**Comment by coolme200** [comment]
第一种可以用 dns.lookup 优先返回 hosts中配置的IP

**Comment by fengmk2** [comment]
当时没有使用lookup是因为 这个 http://nodejs.org/docs/latest/api/dns.html#dns_dns

> Use require('dns') to access this module. All methods in the dns module use C-Ares except for dns.lookup which uses getaddrinfo(3) in a thread pool. C-Ares is much faster than getaddrinfo but the system resolver is more constant with how other programs operate. When a user does net.connect(80, 'google.com') or http.get({ host: 'google.com' }) the dns.lookup method is used. Users who need to do a large number of lookups quickly should use the methods that go through C-Ares.

**Comment by fengmk2** [comment]
我修改成默认的 lookup 吧
